### ISSUE TITLE
The open dataverse button on the main page isnt working

### ISSUE THREAD

**Issue by subikshabamboo** [multiverseweb/Dataverse#12] opened 2024-10-01 19:04 UTC

**Comment by multiverseweb** [comment] 2024-10-01 19:28
Are you talking about this `Get Dataverse` Button?

![image](https://github.com/user-attachments/assets/a3f52ae6-5259-4cef-b18e-6db414368fc5)

**Comment by Devanshu1603** [comment] 2024-10-01 22:14
please assign me this under gssoc. i can fix it

**Comment by multiverseweb** [comment] 2024-10-02 07:19
@subikshabamboo @Devanshu1603 But how will you make the button work? The software is currently under development and its not ready for installation. The button is supposed to inform users that `Dataverse will be available for installation soon` and that's what it is doing. Let me know if I'm missing your point.

**Comment by Devanshu1603** [comment] 2024-10-02 07:25
@multiverseweb i think we should pop up an alert that the software is under maintainance and Dataverse will be available for installation soon. the problem is that on clicking on the button alert is not showing . i want to fix this issue. please assign this to me under gssoc-ext level.will be haapy to contribute

**Comment by multiverseweb** [comment] 2024-10-02 07:47
@Devanshu1603 okay now I see the problem. Actually, the button is showing the alert but there is an image over the button with `opacity: 0;`. That is why the button is not detecting hover.
To fix the issue, you need to give margin to the image on top, so that it stays below the button.
You can see the alert here:
![Screenshot 2024-10-02 131256](https://github.com/user-attachments/assets/fccc2d59-18e0-43eb-905b-48ab0be7cd76)

I'm assigning it to you. Let me know if you need further clarification.

**Comment by Devanshu1603** [comment] 2024-10-02 07:52
thanks @multiverseweb  for assigning me this

**Closed** 2024-10-02 13:25 UTC
Labels: hacktoberfest-accepted, gssoc-ext, level1

**Comment by Devanshu1603** [comment] 2024-10-02 13:27
why haven't you merged it as a contribution.as the button is working properly now
